version: '3'

services:
  flask-container:
    build: ./flask  
    depends_on:
      - redis-container
    ports:
      - "5000:80"
    networks:
      - my_network

  redis-container:
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  csharp-container:
    build:
      context: ./c#
    depends_on:
      - redis-container
      - postgres
    networks:
      - my_network

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network  

networks:
  my_network:
    driver: bridge

volumes: 
  postgres_data:
